Import(['*'])

env = env.Clone()

env.Prepend(LIBS = [
    dsurf,
    lex,
    image,
    stats,
    timer,
])

main = [
    'codedid.cpp',
    'dsurf.cpp',
    'environ.cpp',
    'geomrend.cpp',
    'geomutil.cpp',
    'glutils.cpp',
    'main.cpp',
    'misc.cpp',
    'options.cpp',
    'rc.cpp',
    'test.cpp',
    'winsys.cpp',
]

tests = [
    'tapi2.cpp',
    'tbasic.cpp',
    'tbasicperf.cpp',
    'tbinding.cpp',
    'tblend.cpp',
    'tchgperf.cpp',
    'tclipflat.cpp',
    'tdepthstencil.cpp',
    'tfbo.cpp',
    'tfpexceptions.cpp',
    'tfragprog1.cpp',
    'tgetstr.cpp',
    'tglsl1.cpp',
    'tlogicop.cpp',
    'tmaskedclear.cpp',
    'tmultitest.cpp',
    'toccluqry.cpp',
    'torthpos.cpp',
    'tpaths.cpp',
    'tpgos.cpp',
    'tpixelformats.cpp',
    'tpointatten.cpp',
    'treadpix.cpp',
    'treadpixperf.cpp',
    'trgbtris.cpp',
    'tscissor.cpp',
    'tshaderapi.cpp',
    'tstencil2.cpp',
    'tteapot.cpp',
    'ttexcombine4.cpp',
    'ttexcombine.cpp',
    'ttexcube.cpp',
    'ttexenv.cpp',
    'ttexgen.cpp',
    'ttexrect.cpp',
    'ttexture_srgb.cpp',
    'tvertattrib.cpp',
    'tvertarraybgra.cpp',
    'tvertprog1.cpp',
    'tvtxperf.cpp',
]

if env['platform'] != 'windows':
    tests += [
        'tpbo.cpp',
        'tpointsprite.cpp',
        'ttexswizzle.cpp',
        'ttexunits.cpp',
    ]

glean = env.Program(
    target = 'glean',
    source = main + tests,
)

env.Default(glean)

env.Install('/bin', glean)
