Import(['*'])

if env['glut']:
    env = env.Clone()

    env.Prepend(LIBS = [image])

    showtiff = env.Program('showtiff', ['main.cpp'])

    env.Default(showtiff)

    env.Install('/bin', showtiff)
