import os.path

Import(['*'])

if env['glut']:
    env = env.Clone()

    env.Prepend(LIBS = [image])

    showtiff = env.Program('showtiff', ['main.cpp'])

    env.Default(showtiff)

    bin_dir = os.path.join(env['prefix'], 'bin')
    env.Install(bin_dir, showtiff)
    env.Alias('install', bin_dir)
