import os.path

Import(['*'])

if env['glut']:
    env = env.Clone()

    env.Prepend(LIBS = [image])

    difftiff = env.Program('difftiff', ['main.cpp'])

    env.Default(difftiff)

    bin_dir = os.path.join(env['prefix'], 'bin')
    env.Install(bin_dir, difftiff)
    env.Alias('install', bin_dir)
