Import(['*'])

if env['glut']:
    env = env.Clone()

    env.Prepend(LIBS = [image])

    difftiff = env.Program('difftiff', ['main.cpp'])

    env.Default(difftiff)

    env.Install('/bin', difftiff)
