import os.path

Import(['*'])

env = env.Clone()

env.Prepend(LIBS = [dsurf, lex])

showvis = env.Program('showvis', ['main.cpp'])

env.Default(showvis)

bin_dir = os.path.join(env['prefix'], 'bin')
env.Install(bin_dir, showvis)
env.Alias('install', bin_dir)
