Import(['*'])

if env['glut']:
    env = env.Clone()

    env.Prepend(LIBS = [dsurf, lex])

    showvis = env.Program('showvis', ['main.cpp'])

    env.Default(showvis)

    env.Install('/bin', showvis)
